### ISSUE TITLE
Le téléchargement ne fonctionne pas sur firefox mobile

### ISSUE THREAD

**Issue by bbinet** [nyroDev/covid19AttestPwa#2]
Same issue as:

https://github.com/LAB-MI/deplacement-covid-19/issues/37

**Comment by nyroDev** [comment]
Bonjour @bbinet,
je viens de tester et cela a fonctionner sur mon téléphone.
Quelle version d'Android et de Firefox utilisez-vous ?

**Comment by nyroDev** [comment]
Ca fonctionne dans le navigateur, mais en mode installé, car il réouvre un onglet qui a donc perdu la référence du Blob stocké en mémoire.
A voir si l'utilisation d'un data:uri résoudrait le problème, mais ce serait peut-être trop long.

Autre solution, déplacer toute la génération du PDF côté service worker et retourner le PDF avec une entête correcte de téléchargement (octet-stream). Cette solution implique que le service worker soit installé et actif pour fonctionner.

**Comment by julienw** [comment]
Les data:uri en navigation "top level" ne marchent pas dans chrome, semble-t-il pour des raisons de sécurité.
Je viens de vérifier l'appli officielle, et ça devrait marcher dans Firefox Release.

**Comment by bbinet** [comment]
@nyroDev Merci d'avoir investigué.
Pour le moment j'ai installé chromium et ça fonctionne bien.

**Comment by nyroDev** [comment]
Bonsoir @bbinet,
Je viens de mettre à jour le code, et à priori, ça fonctionne maintenant correctement sur Firefox, installé ou pas.

Vous confirmez ?

**Comment by bbinet** [comment]
Non, le téléchargement échoue encore pour moi sur https://attest.nyro.com/
avec Firefox mobile nightly.

On Sunday, April 12, 2020, Nyro <notifications@github.com> wrote:
> Bonsoir @bbinet,
> Je viens de mettre à jour le code, et à priori, ça fonctionne maintenant
correctement sur Firefox, installé ou pas.
>
> Vous confirmez ?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or unsubscribe.<
https://ci5.googleusercontent.com/proxy/IHEA0nPE3xlYYmu0yqhhLynvxKeZygs0-x9dMROtaAelRjrnceelKrkYkIpBJoXs5FPUNjuwNsPaMDvvRADGS4C-TGk7lZlf4av97Rc-UucAC6nBxsaEe0OMwS8iCUs9yr_D02UzYJLjSoVDl1kYo4NzlbLc9jW4y3e2YkL_nolc4zxI8cKLaBzyCH52Mhvu0SrF4GpNDXPkJh0xZG0jMu2LRJN2t9vpDWWvggHeRw=s0-d-e1-ft#https://github.com/notifications/beacon/AAAST6N2A5V6SNNF6O7CQXLRMDSAZA5CNFSM4MESLAS2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOESBFQ4Y.gif>

**Comment by nyroDev** [comment]
Avec la version 10 de la pwa ?
De mon côté, je n'ai plus le problème

**Comment by bbinet** [comment]
Ah non, j'avais testé la version en ligne sur https://attest.nyro.com/ en
pensant que c'était la dernière version mais il semble que c'est la V9.
Je vais ressayer dés que je trouve un moment.
Merci.

**Comment by bbinet** [comment]
Pour info, avec quelques moi de retard, je confirme que ça fonctionne bien sous Firefox.
Merci!
